import Fluent

struct CreateSchemaV1: AsyncMigration {
    func prepare(on db: Database) async throws {
        try await db.schema(UserModel.schema)
            .id()
            .field("name", .string, .required)
            .field("email", .string)
            .field("created_at", .datetime)
            .create()
        try await db.schema(WorkspaceModel.schema)
            .id()
            .field("name", .string, .required)
            .field("owner_id", .uuid, .required, .references(UserModel.schema, "id"))
            .field("plan", .string, .required)
            .field("created_at", .datetime)
            .create()
        try await db.schema(WorkspaceMemberModel.schema)
            .id()
            .field("workspace_id", .uuid, .required, .references(WorkspaceModel.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references(UserModel.schema, "id", onDelete: .cascade))
            .field("role", .string, .required)
            .unique(on: "workspace_id", "user_id")
            .create()
        try await db.schema(DeviceTokenModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references(UserModel.schema, "id", onDelete: .cascade))
            .field("workspace_id", .uuid, .required, .references(WorkspaceModel.schema, "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("token_hash", .string, .required)
            .field("created_at", .datetime)
            .field("last_used_at", .datetime)
            .field("revoked_at", .datetime)
            .unique(on: "token_hash")
            .create()
        try await db.schema(ProjectModel.schema)
            .id()
            .field("workspace_id", .uuid, .required, .references(WorkspaceModel.schema, "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("context", .string, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()
        try await db.schema(MeetingModel.schema)
            .id()
            .field("workspace_id", .uuid, .required, .references(WorkspaceModel.schema, "id", onDelete: .cascade))
            .field("project_id", .uuid, .required, .references(ProjectModel.schema, "id", onDelete: .cascade))
            .field("title", .string, .required)
            .field("title_is_auto", .bool, .required)
            .field("started_at", .datetime, .required)
            .field("duration_seconds", .double, .required)
            .field("status", .string, .required)
            .field("source", .string, .required)
            .field("imported_file_name", .string)
            .field("error_message", .string)
            .field("speaker_names", .string, .required)
            .field("notes", .string, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()
        try await db.schema(ActionItemModel.schema)
            .id()
            .field("meeting_id", .uuid, .required, .references(MeetingModel.schema, "id", onDelete: .cascade))
            .field("task", .string, .required)
            .field("owner", .string)
            .field("due", .string)
            .field("done", .bool, .required)
            .field("is_manual", .bool, .required)
            .field("position", .int, .required)
            .field("updated_at", .datetime)
            .create()
        try await db.schema(TranscriptModel.schema)
            .id()
            .field("meeting_id", .uuid, .required, .references(MeetingModel.schema, "id", onDelete: .cascade))
            .field("segments", .string, .required)
            .field("created_at", .datetime)
            .unique(on: "meeting_id")
            .create()
        try await db.schema(SummaryModel.schema)
            .id()
            .field("meeting_id", .uuid, .required, .references(MeetingModel.schema, "id", onDelete: .cascade))
            .field("json", .string, .required)
            .field("markdown", .string, .required)
            .field("provider", .string, .required)
            .field("created_at", .datetime)
            .unique(on: "meeting_id")
            .create()
        try await db.schema(AudioFileModel.schema)
            .id()
            .field("meeting_id", .uuid, .required, .references(MeetingModel.schema, "id", onDelete: .cascade))
            .field("kind", .string, .required)
            .field("file_name", .string, .required)
            .field("byte_size", .int, .required)
            .field("sha256", .string)
            .field("created_at", .datetime)
            .unique(on: "meeting_id", "kind")
            .create()
        try await db.schema(JobModel.schema)
            .id()
            .field("workspace_id", .uuid, .required, .references(WorkspaceModel.schema, "id", onDelete: .cascade))
            .field("meeting_id", .uuid, .required, .references(MeetingModel.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references(UserModel.schema, "id", onDelete: .cascade))
            .field("steps", .string, .required)
            .field("status", .string, .required)
            .field("progress", .string)
            .field("error", .string)
            .field("attempts", .int, .required)
            .field("created_at", .datetime)
            .field("started_at", .datetime)
            .field("finished_at", .datetime)
            .create()
        try await db.schema(SettingModel.schema)
            .id()
            .field("workspace_id", .uuid, .required, .references(WorkspaceModel.schema, "id", onDelete: .cascade))
            .field("key", .string, .required)
            .field("value", .string, .required)
            .field("updated_at", .datetime)
            .unique(on: "workspace_id", "key")
            .create()
    }

    func revert(on db: Database) async throws {
        for schema in [SettingModel.schema, JobModel.schema, AudioFileModel.schema, SummaryModel.schema, TranscriptModel.schema,
                       ActionItemModel.schema, MeetingModel.schema, ProjectModel.schema, DeviceTokenModel.schema,
                       WorkspaceMemberModel.schema, WorkspaceModel.schema, UserModel.schema] {
            try await db.schema(schema).delete()
        }
    }
}
